# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million, find the sum of the
# even-valued terms.

MAX = 4_000_000

def fib_enumerator(max)
  fib = Enumerator.new do |y|
    a = b = 1
    while a <= max
      y.yield a
      a, b = b, a+b
    end
    fib
  end
end

sum = fib_enumerator(MAX).select{ |n| n.even? }.reduce(:+)

puts "The sum of the even-valued terms and do not exceed four million in Fibonacci sequence is #{sum}"
